server:
  port: 9001

spring:
  application:
    name: car
  data:
    mongodb:
      uri: mongodb://env-base:27017/car
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy # ?????
