server:
  port: 9000

spring:
  application:
    name: duitang
#  这里先不用 mysql 了
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://env-base:3306/duitang
#    username: root
#    password: 1111
  data:
    mongodb:
      uri: mongodb://env-base:27017/duitang
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy # 自动转驼峰
    redis:
      host: env-base
      port: 6379

mybatis-plus:
  type-aliases-package: org/cyk/ktduitang/domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印 sql
    map-underscore-to-camel-case: true # 是否开启下划线和驼峰的映射
    cache-enabled: false # 是否开启二级缓存
  global-config:
    db-config:
      id-type: auto # 默认雪花算法，另外还有 auto(自增id) assign_uuid(uuid)
      update-strategy: not_null # 更新策略: 只更新非空字段

