server:
  port: 9000

spring:
  application:
    name: user-prod
  cloud:
    nacos:
      server-addr: env-base:8848
  datasource:
    url: jdbc:mysql://env-base:3306/redbook_db?characterEncoding=utf8&useSSL=false
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: env-base
    port: 6379
  data:
    mongodb:
      uri: mongodb://192.168.73.3:27017/redbook_db
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy # 自动转驼峰
  rabbitmq:
    host: env-base # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: root # 用户名
    password: 1111 # 密码
  # 时间处理
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  # 配置静态资源路径
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /apps/image/user/**
  web:
    resources:
      static-locations: file:/apps/image/user/


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印 sql
    map-underscore-to-camel-case: true # 是否开启下划线和驼峰的映射
    cache-enabled: false # 是否开启二级缓存
  global-config:
    db-config:
      id-type: auto # 默认雪花算法，另外还有 auto(自增id) assign_uuid(uuid)
      update-strategy: not_null # 更新策略: 只更新非空字段

save-path:
  avatar: /apps/image/user/
