server:
  port: 10010

spring:
  application:
    name: gateway
  data:
    redis:
      host: env-base
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: env-base:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: album-service
          uri: lb://album
          predicates:
            - Path=/album/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: true
            maxAge: 360000 # 这次跨域检测的有效期（为例减少性能损耗，在有效时间内，浏览器将不在发起询问，直接放行通过）
