grpc:
  server:
    port: 9000

spring:
  application:
    name: user
  main:
    web-application-type: none
  data:
    mongodb:
      uri: mongodb://env-base:27017/duitang
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy # 自动转驼峰
    redis:
      host: env-base
      port: 6379

